// Aware Trade Macro Monitor -- Data
// Update this file when new economic data is released
// Last updated: June 12, 2026

const monitorData = {
  updatedDate: "June 11, 2026  --  PPI and Claims updated. UMich June prelim releases June 12.",
  indicators: [
    {
      id: "cpi",
      label: "CPI (May)",
      value: "4.2%",
      sub: "+0.5% this month",
      note: "3-year high. Energy up 23.5% over the past year.",
      signal: "red",
      signalLabel: "HOT",
      category: "inflation",
      behind: [
        { stat: "Real impact on a $60K household", value: "−$2,520/yr", context: "4.2% inflation on typical household spending." },
        { stat: "Share of May's increase from energy", value: "Over 60%", context: "Most of the spike was gasoline. Core inflation is softer,." },
        { stat: "Months above 3.5% in a row", value: "2", context: "April was 3.8%. May is 4.2%. The trend is moving in the." },
      ],
    },
    {
      id: "core-cpi",
      label: "Core CPI (May)",
      value: "2.9%",
      sub: "+0.2% this month",
      note: "Strips out food and energy. Tariff pressure is muted.",
      signal: "yellow",
      signalLabel: "WATCH",
      category: "inflation",
    },
    {
      id: "ppi",
      label: "PPI (May)",
      value: "−0.2%",
      sub: "Month over month. Forecast was +0.7%. First monthly.",
      note: "Wholesale inflation cooling. Gives the Fed more room. Pipeline.",
      signal: "green",
      signalLabel: "COOL",
      category: "inflation",
    },
    {
      id: "fed",
      label: "Fed Funds Rate",
      value: "3.50–3.75%",
      sub: "No change expected. Next meeting: June 16–17.",
      note: "New Chair Kevin Warsh. April vote was 8 to 4 to hold.",
      signal: "yellow",
      signalLabel: "HOLD",
      category: "monetary",
      behind: [
        { stat: "Votes to cut rates at last meeting", value: "4 out of 12", context: "The most divided Fed vote in over three decades." },
        { stat: "Real interest rate (adjusted for inflation)", value: "About −0.5%", context: "At 3.625% midpoint against 4.2% CPI, the real rate is still." },
        { stat: "Market odds of a cut in June", value: "Under 5%", context: "After yesterday's CPI report, markets have essentially." },
      ],
    },
    {
      id: "jobs",
      label: "Payrolls (May)",
      value: "172,000",
      sub: "May 2026. Forecasters expected 85,000. Beat by more than double.",
      note: "Strong headline -- but composition tells a different story. Healthcare and leisure/hospitality doing the heavy lifting.",
      signal: "green",
      signalLabel: "STRONG",
      category: "labor",
      behind: [
        { stat: "Where the jobs are", value: "Healthcare + leisure/hospitality", context: "Healthcare added 52,000. Leisure and hospitality added 39,000. These are not high-wage, high-productivity sectors. They are the sectors that hire when upper-K consumers still go to restaurants and medical visits -- not a sign of broad economic strength." },
        { stat: "Where jobs are NOT", value: "Manufacturing, finance, tech", context: "Manufacturing employment flat. Financial services down from peak by 107,000. Technology sector cutting 1,136 jobs per day. The high-wage, high-multiplier sectors are contracting while low-wage service sectors add." },
        { stat: "Prior month revisions", value: "+93,000 combined", context: "March and April were revised up by a combined 93,000. The BLS frequently revises initial readings. The trend matters more than any single month." },
        { stat: "K-shape signal", value: "Upper-K still spending, lower-K still serving", context: "Leisure and hospitality growth means upper-K households still eat out and travel. When Stage 3 contagion arrives in Q4 and upper-K tightens, these jobs are the first to go." },
      ],
    },
    {
      id: "unemployment",
      label: "Unemployment Rate",
      value: "4.3%",
      sub: "Unchanged. Has held between 4.3% and 4.5% since July.",
      note: "The broader U-6 rate is 8.1%. Long-term unemployed: 27.5% of all.",
      signal: "yellow",
      signalLabel: "WATCH",
      category: "labor",
    },
    {
      id: "wages",
      label: "Wage Growth",
      value: "+3.4%",
      sub: "Year over year. +0.3% this month. CPI running at 4.2%.",
      note: "Nominal wages up 3.4%. Real wages -0.8%. Every worker is getting a pay cut in purchasing power terms.",
      signal: "red",
      signalLabel: "NEGATIVE REAL",
      category: "labor",
      behind: [
        { stat: "Nominal vs real", value: "+3.4% nominal / -0.8% real", context: "Subtract 4.2% CPI from 3.4% wage growth and every worker lost purchasing power this month. Has been negative since early 2025." },
        { stat: "Leisure and hospitality", value: "+4.1% -- above average", context: "The sector adding the most jobs is seeing above-average wage growth but from a lower base. A 4% raise on $18/hr is not the same economic impact as a 3% raise on $45/hr." },
        { stat: "Professional services", value: "+2.8% -- below inflation", context: "Higher-wage sectors are seeing slower wage growth than inflation. The upper-K income squeeze is real even if less visible." },
        { stat: "What this means", value: "Consumers are getting poorer", context: "The retail sales headline looks positive partly because people are spending more dollars to buy the same amount. Real consumption is flat to falling for most households." },
      ],
    },
    {
      id: "jobless",
      label: "Weekly Jobless Claims",
      value: "242,000",
      sub: "Highest since August 2023. Forecast was 220,000.",
      note: "Jumped 22,000 above forecast. Labor market cracks appearing beneath.",
      signal: "red",
      signalLabel: "RISING",
      category: "labor",
    },
    {
      id: "umich",
      label: "Consumer Sentiment (June prelim.)",
      value: "48.9",
      sub: "June 12, 2026. Up from 44.8 May final. Still near.",
      note: "Relief rally, not recovery. Gas dropped $4.56 to $4.12 -- prices.",
      signal: "red",
      signalLabel: "NEAR LOWS",
      category: "consumer",
      behind: [
        { stat: "June prelim vs May final", value: "48.9 vs 44.8", context: "Up 4.1 points. Relief from gas prices flattening, not." },
        { stat: "Gas price move", value: "$4.56 to $4.12 over 3 weeks", context: "Prices stopped climbing. $4.12 is still very high -- the." },
        { stat: "Long-run inflation expectations", value: "3.9% -- up from 3.5%", context: "Rose despite the sentiment bump. Consumers expect inflation." },
        { stat: "Who drove the improvement", value: "Lower-income households", context: "Families with thin margins felt gas price relief most. Any." },
        { stat: "The bottom line", value: "Still near historic lows", context: "48.9 means things did not get worse this month. It does not." },
      ],
        },
    {
      id: "energy",
      label: "Energy Prices (May)",
      value: "+23.5%",
      sub: "Year over year. Gasoline is the main driver.",
      note: "Iran conflict is keeping pressure on.",
      signal: "red",
      signalLabel: "CRITICAL",
      category: "inflation",
    },
    {
      id: "snap",
      label: "SNAP Benefit Cuts",
      value: "Oct 1",
      sub: "$187 billion cut over 10 years",
      note: "States must cover 75% of admin costs. Some may limit or exit the.",
      signal: "red",
      signalLabel: "STRUCTURAL",
      category: "stress",
    },
    {
      id: "fincen",
      label: "FinCEN Banking Advisory",
      value: "June 5",
      sub: "Banks directed to flag customers by immigration status",
      note: "Using an ITIN is now a red flag. So is sharing an address.",
      signal: "red",
      signalLabel: "ACTIVE",
      category: "money",
    },
    {
      id: "cc-delinquency",
      label: "Credit Card Delinquency",
      value: "2.9%",
      sub: "Q1 2026. Above pre-pandemic level of 2.6%.",
      note: "Headline is improving. Small bank rate is 6.4%  --  more than.",
      signal: "yellow",
      signalLabel: "ELEVATED",
      category: "stress",
    },
    {
      id: "auto-delinquency",
      label: "Auto Loan Delinquency",
      value: "5.6%",
      sub: "Q1 2026. 90+ days past due. Near post-financial-crisis.",
      note: "Subprime auto at record highs. Car payments are the last bill.",
      signal: "red",
      signalLabel: "STRESS",
      category: "stress",
    },
    {
      id: "mortgage-delinquency",
      label: "Mortgage Delinquency",
      value: "4.44%",
      sub: "Q1 2026. Up 40 basis points from a year ago.",
      note: "FHA loans at 11.52%. Foreclosure starts rising.",
      signal: "red",
      signalLabel: "RISING",
      category: "stress",
    },
    {
      id: "total-household-debt",
      label: "Total Household Debt",
      value: "$18.8 trillion",
      sub: "Q1 2026. Up $18 billion from Q4 2025.",
      note: "4.8% of all outstanding debt is in some stage of delinquency.",
      signal: "yellow",
      signalLabel: "WATCH",
      category: "debt",
    },
    {
      id: "sp500",
      label: "S&P 500",
      value: "7,267",
      sub: "June 10, 2026. Down 1.62% on the day.",
      note: "Down from the April high. Dow fell 1.87%, Nasdaq 1.98% on Tuesday.",
      signal: "yellow",
      signalLabel: "RETREATING",
      category: "markets",
      behind: [
        { stat: "Year-to-date performance", value: "Volatile", context: "The S&P hit highs in late 2025, pulled back sharply on." },
        { stat: "Implied future annual return (CAPE-based)", value: "1.9%", context: "At current valuations, the Shiller CAPE model implies a." },
        { stat: "Tuesday's selloff driver", value: "Hot CPI + rising claims", context: "Wednesday's CPI at 4.2% and Thursday's jobless claims at." },
      ],
    },
    {
      id: "cape",
      label: "Shiller CAPE Ratio",
      value: "39.9",
      sub: "June 1, 2026. Historical median: 16.1.",
      note: "23.9% above its own long-term average of 32.2. Implies very low.",
      signal: "red",
      signalLabel: "OVERVALUED",
      category: "markets",
    },
    {
      id: "vix",
      label: "VIX  --  Fear Index",
      value: "22.2",
      sub: "June 10, 2026. Up 11.8% on the day.",
      note: "52-week range: 13.4 to 35.3. Elevated but off the March peak of.",
      signal: "yellow",
      signalLabel: "ELEVATED",
      category: "markets",
    },
    {
      id: "credit-spreads",
      label: "High Yield Credit Spreads",
      value: "~300 bps",
      sub: "Mid-April 2026. Tightest since June 2007.",
      note: "Spreads say everything is fine. Default rates say otherwise.",
      signal: "red",
      signalLabel: "COMPLACENT",
      category: "markets",
    },
    {
      id: "sixty-forty",
      label: "60/40 Portfolio",
      value: "Under pressure",
      sub: "Stocks and bonds falling together. The hedge is broken.",
      note: "When inflation is high, bonds do not offset stock losses.",
      signal: "red",
      signalLabel: "BROKEN",
      category: "markets",
    },
    {
      id: "ten-year",
      label: "10-Year Treasury Yield",
      value: "~4.5%",
      sub: "June 10, 2026. The benchmark rate for everything.",
      note: "Mortgage rates, auto loans, corporate debt, and the U.S.",
      signal: "yellow",
      signalLabel: "ELEVATED",
      category: "money",
    },
    {
      id: "treasury-auction",
      label: "Treasury Auction Demand",
      value: "Weakening",
      sub: "Bid-to-cover declining on 10 and 30-year auctions. Term premium rising.",
      note: "Primary dealers absorbing more supply -- means the market did not want the paper at that yield.",
      signal: "red",
      signalLabel: "WATCH",
      category: "money",
      behind: [
        { stat: "What bid-to-cover measures", value: "Demand per dollar of supply", context: "Above 2.5x is healthy. Below 2.3x on 10 and 30-year auctions is a stress signal. Primary dealers must absorb what the market refuses." },
        { stat: "Top foreign holders Feb 2026", value: "Japan $1.24T, UK $897B, China $693B", context: "China has been reducing Treasury holdings since 2022. Japan and UK stable but any coordinated reduction requires domestic buyers at higher yields." },
        { stat: "Term premium", value: "Rising -- ACM model", context: "The extra yield investors demand to hold long bonds rather than rolling short paper. Rising term premium means the market does not trust the fiscal trajectory." },
        { stat: "The bond vigilante mechanism", value: "Market sets the long end", context: "The Fed controls short-term rates. The market controls long-term rates. Weak auction demand pushes 10 and 30-year yields up regardless of what the Fed does. Mortgage rates follow." },
        { stat: "The Warsh cut ceiling", value: "Fed can cut -- long yields may not follow", context: "Even if Warsh cuts the Fed funds rate, the long end may keep rising if fiscal credibility erodes. Fed cutting with 30-year yields rising simultaneously is the Japan scenario." },
      ],
    },
    {
      id: "mortgage-rate",
      label: "30-Year Mortgage Rate",
      value: "6.55%",
      sub: "June 11, 2026. Up from 6.48% last week. Freddie Mac:.",
      note: "Hopes for sub-6% rates in 2026 keep fading.",
      signal: "red",
      signalLabel: "STUCK",
      category: "consumer",
    },
    {
      id: "home-affordability",
      label: "Home Price to Income Ratio",
      value: "~7.2x",
      sub: "2026 estimate. Historical average: ~3.5x.",
      note: "Buying a home now requires more than 7 years of gross household.",
      signal: "red",
      signalLabel: "CRISIS",
      category: "consumer",
    },
    {
      id: "savings-rate",
      label: "Personal Savings Rate",
      value: "2.6%",
      sub: "April 2026. BEA. Down from 4.5% in January 2026.",
      note: "The household buffer is thinning. Historical average is 8.4%.",
      signal: "red",
      signalLabel: "DEPLETING",
      category: "consumer",
    },
    {
      id: "retail-sales",
      label: "Retail Sales (April / May due Jun 17)",
      value: "+0.5%",
      sub: "April month over month. May report releases June 17 --.",
      note: "Nominal numbers look healthy but are inflated by high gas prices..",
      signal: "yellow",
      signalLabel: "WATCH",
      category: "consumer",
      behind: [
        { stat: "The nominal number is misleading", value: "Gas inflates the headline", context: "Retail sales are not adjusted for inflation. When gas." },
        { stat: "What is actually being cut", value: "Clothing, furniture, restaurants", context: "Clothing and furniture sales have dropped. Restaurant sales." },
        { stat: "Where spending is shifting", value: "Online and warehouse clubs", context: "Online retailers seeing steady growth -- people buy online." },
        { stat: "How remaining spending is financed", value: "Savings drain and credit cards", context: "Tax refund season is over. People are increasingly draining." },
        { stat: "What to watch June 17", value: "Ex-gas retail sales number", context: "If the ex-gasoline retail sales number is flat or negative,." },
      ],
    },
    {
      id: "wti",
      label: "WTI Crude Oil",
      value: "~$91/barrel",
      sub: "June 10–11, 2026. Brent near $94.",
      note: "Trump says Iran deal is close -- Tehran denies. If deal closes:.",
      signal: "red",
      signalLabel: "ELEVATED",
      category: "inflation",
      behind: [
        { stat: "Price one year ago", value: "~$64/barrel", context: "Oil is up roughly 42% year over year." },
        { stat: "EIA peak forecast", value: "$115/barrel Q2 2026", context: "The Energy Information Administration forecast Brent." },
        { stat: "Strait of Hormuz status", value: "Near-total closure", context: "The Strait carries roughly 20% of global oil supply." },
        { stat: "Impact on every other price", value: "Diesel, fertilizer, transportation", context: "Oil does not just affect gas prices. Diesel moves freight." },
      ],
    },
    {
      id: "tech-layoffs",
      label: "Tech Layoffs (2026 YTD)",
      value: "184,000+",
      sub: "Through June 2026. 1,136 layoffs per day -- double.",
      note: "48% explicitly attributed to AI displacement. Amazon, Oracle, Meta,.",
      signal: "red",
      signalLabel: "ACCELERATING",
      category: "labor",
      behind: [
        { stat: "2026 vs 2025 pace", value: "1,136/day vs 564/day", context: "The 2026 pace is double 2025. 33% increase over same period." },
        { stat: "AI attribution rate", value: "48% of Q1 cuts", context: "Nearly half of Q1 2026 tech layoffs explicitly attributed." },
        { stat: "Largest cuts", value: "Amazon 30K, Oracle 30K, Meta 8K", context: "All announced record AI capital expenditure the same." },
        { stat: "Young engineer impact", value: "Software dev employment under 26 down 20% since 2024", context: "Stanford HAI data. AI is not just displacing entry-level." },
        { stat: "The Aware Trade thesis connection", value: "Workers built the tool that eliminated their leverage", context: "Project Maven 2018 to 2026: the same workers who built AI." },
      ],
    },
    {
      id: "nfib",
      label: "NFIB Small Business Optimism",
      value: "95.3",
      sub: "May 2026. Below 52-year average of 98.0 for second.",
      note: "Uncertainty index at 91  --  well above historical average of 68.",
      signal: "yellow",
      signalLabel: "FRAGILE",
      category: "labor",
    },
    {
      id: "fed-debt",
      label: "Federal Debt",
      value: "$39 trillion",
      sub: "Gross debt eclipsed $39T March 17 2026. Debt-to-GDP.",
      note: "Interest payments hit $1T annually -- surpassing defense spending.",
      signal: "red",
      signalLabel: "CRITICAL",
      category: "debt",
    },
    {
      id: "treasury-auction",
      label: "Treasury Auction Demand",
      value: "Watch",
      sub: "Bid-to-cover ratios declining on longer maturities.",
      note: "Weak auctions signal insufficient demand at current yields --.",
      signal: "yellow",
      signalLabel: "WATCH",
      category: "debt",
    },
    {
      id: "cre-office",
      label: "CRE Office Loan Delinquency",
      value: "12.34%",
      sub: "Record high as of January 2026. Trepp data.",
      note: "Office vacancy above 20% nationally. $1 trillion in CRE loans.",
      signal: "red",
      signalLabel: "STRESS",
      category: "debt",
    },
    {
      id: "private-equity",
      label: "Private Equity Stress",
      value: "$1T unrealized",
      sub: "Estimated unrealized assets at mid-2025. PwC estimate.",
      note: "62% of pension funds exceeded PE allocation targets.",
      signal: "yellow",
      signalLabel: "FROZEN",
      category: "debt",
    },
    {
      id: "dxy",
      label: "U.S. Dollar Index (DXY)",
      value: "~100",
      sub: "June 11, 2026. Down ~10% from Jan 2025 peak of 109+.",
      note: "Steepest H1 decline since 1973.",
      signal: "yellow",
      signalLabel: "WEAKENING",
      category: "dollar",
    },
    {
      id: "dollar-reserves",
      label: "Dollar Share of Global Reserves",
      value: "~57%",
      sub: "Q3 2025 IMF COFER. Lowest since 1995.",
      note: "Down from 72% in 2001. Structural decline confirmed.",
      signal: "yellow",
      signalLabel: "DECLINING",
      category: "dollar",
    },
    {
      id: "gold-reserves",
      label: "Central Bank Gold Purchases",
      value: "1,000+ tonnes",
      sub: "Third consecutive year above 1,000 tonnes. 2024 total:.",
      note: "More than double the 473-tonne annual average from 2010 to 2021.",
      signal: "red",
      signalLabel: "ACCELERATING",
      category: "dollar",
    },
    {
      id: "mbridge",
      label: "mBridge  --  Cross-Border CBDC",
      value: "$55.5B settled",
      sub: "2,500x increase since 2022. 15-second settlement. No.",
      note: "China, UAE, Saudi Arabia, Thailand, Hong Kong. BIS withdrew Oct.",
      signal: "red",
      signalLabel: "ACTIVE",
      category: "dollar",
    },
    {
      id: "agora",
      label: "Project Agora  --  Western Response",
      value: "Real-value testing 2026",
      sub: "7 central banks, 40+ institutions. Prototype confirmed.",
      note: "Fed NY, Bank of England, Bank of Japan.",
      signal: "yellow",
      signalLabel: "BUILDING",
      category: "dollar",
    },
    {
      id: "petrodollar",
      label: "Petrodollar Agreement",
      value: "Expired",
      sub: "June 9, 2024. No renewal. No replacement agreement.",
      note: "Saudi Arabia can now price oil in any currency.",
      signal: "yellow",
      signalLabel: "WATCH",
      category: "dollar",
    },
  ],
    contagion: [
    { stage: "Stage 1", status: "complete", label: "Lower-K Balance Sheets Broke", date: "2023-2025",
      text: "Subprime auto delinquency hit record highs. Small bank credit card delinquency reached 6.4%. FHA mortgage delinquency.", level: "red" },
    { stage: "Stage 2", status: "active", label: "Lower-K Spending Contracting", date: "Now  --  Q3 2026",
      text: "NFIB retail sector most pessimistic of all industries. Jobless claims jumped to 242,000. Small business hiring at.", level: "red" },
    { stage: "Stage 3", status: "approaching", label: "Corporate Earnings Miss  --  Lower-K Visible", date: "Q4 2026 / Jan-Feb 2027",
      text: "SNAP cuts land October 1. Energy bills peak seasonally. Lower-K spending cliff becomes visible in earnings for the.", level: "yellow" },
    { stage: "Stage 4", status: "risk", label: "Upper-K Contagion", date: "Q4 2026  --  Q2 2027",
      text: "The upper K is insulated until three things happen: unemployment rises into the professional class, home equity stops.", level: "yellow" },
  ],
  ideas: [
    {
      id: "tbills", theme: "Short-Term Treasury Bills / Notes", weight: "19%",
      signal: "green", conviction: "High", assetClass: "Fixed Income",
      bestAccount: "Taxable -- T-bill interest is exempt from state and local taxes.",
      rationale: "The largest allocation in the model and the right call in this environment. Fed on hold at 3.50-3.75% with no.",
      instruments: [
        { name: "iShares 0-3 Month Treasury Bond ETF", ticker: "SGOV", type: "ETF" },
        { name: "3-Month T-Bills direct via TreasuryDirect.gov", ticker: null, type: "Direct" },
        { name: "Vanguard Ultra-Short Bond ETF", ticker: "VUSB", type: "ETF" },
      ],
      caveat: "Yield advantage disappears when the Fed cuts. Watch September 2026 FOMC closely.",
    },
    {
      id: "domestic-eq", theme: "Domestic Equity", weight: "28%",
      signal: "yellow", conviction: "Medium", assetClass: "Equities",
      bestAccount: "Taxable for long-term holds (capital gains rates).",
      rationale: "Broad domestic equity with a tilt toward industrials, utilities, and energy services. Broad small cap (SCHA).",
      instruments: [
        { name: "US Industrials ETF", ticker: "XLI", type: "ETF" },
        { name: "US Utilities ETF", ticker: "XLU", type: "ETF" },
        { name: "US Oil & Gas Equipment & Services ETF", ticker: "OIH", type: "ETF" },
        { name: "US Large Cap Equal Weight ETF", ticker: "RSP", type: "ETF" },
        { name: "Capital Group Conservative Equity ETF -- active,...", ticker: "CGCV", type: "Active ETF" },
        { name: "Washington Mutual Investors Fund -- value tilt,...", ticker: "AWSHX", type: "Mutual Fund" },
        { name: "O'Shares US Small-Cap Quality Dividend ETF --...", ticker: "OUSM", type: "ETF" },
        { name: "US Biotech ETF", ticker: "XBI", type: "ETF" },
      ],
      caveat: "OUSM screens for quality and dividends within small cap -- better than broad SCHA in this.",
    },
    {
      id: "intl-eq", theme: "International Equity", weight: "20%",
      signal: "yellow", conviction: "Medium", assetClass: "Equities",
      bestAccount: "Taxable -- foreign tax credits on international dividends are only usable in.",
      rationale: "Dollar weakness is the thesis. DXY down 10% from January 2025 peak. When the dollar falls, international.",
      instruments: [
        { name: "Latin America ETF", ticker: "ILF", type: "ETF" },
        { name: "Developed International Markets ETF", ticker: "EFA", type: "ETF" },
        { name: "Emerging Markets ETF", ticker: "EEM", type: "ETF" },
        { name: "Global Metals & Mining Producers ETF", ticker: "PICK", type: "ETF" },
        { name: "Capital Group International Core Equity ETF --...", ticker: "CGIC", type: "Active ETF" },
        { name: "Capital Group New Geography Equity ETF -- active...", ticker: "CGNG", type: "Active ETF" },
      ],
      caveat: "Dollar weakness thesis reverses if Iran conflict drives safe-haven dollar demand. CGNG note:.",
    },
    {
      id: "gold-assets", theme: "Gold, Silver & Industrial Metals", weight: "12.5%",
      signal: "green", conviction: "High", assetClass: "Commodities",
      bestAccount: "IRA -- gold and silver ETFs taxed as collectibles at 28% in taxable accounts.",
      rationale: "Two distinct theses in one allocation. Gold and silver as monetary hedges: when governments print money to.",
      instruments: [
        { name: "Gold Bullion ETF", ticker: "GLD", type: "ETF" },
        { name: "iShares Gold Trust -- lower expense ratio than GLD", ticker: "IAU", type: "ETF" },
        { name: "Sprott Active Gold & Silver Miners ETF -- active,...", ticker: "GBUG", type: "Active ETF" },
        { name: "Precious Metals Miners & Royalty ETF -- passive...", ticker: "GDX", type: "ETF" },
        { name: "Silver Bullion ETF -- monetary and industrial demand", ticker: "SLV", type: "ETF" },
        { name: "abrdn Physical Silver Shares ETF -- lower expense...", ticker: "SIVR", type: "ETF" },
        { name: "abrdn Physical Precious Metals Basket -- gold,...", ticker: "GLTR", type: "ETF" },
        { name: "Sprott Active Metals & Miners ETF -- active,...", ticker: "METL", type: "Active ETF" },
        { name: "Global X Copper Miners ETF -- passive copper miners", ticker: "COPX", type: "ETF" },
        { name: "US Copper Index Fund -- direct copper futures, K-1,...", ticker: "CPER", type: "ETF" },
      ],
      caveat: "Gold and silver ETFs (GLD, IAU, SLV, SIVR) are taxed as collectibles at 28% in taxable.",
    },
    {
      id: "bonds", theme: "Bonds", weight: "15%",
      signal: "yellow", conviction: "Medium", assetClass: "Fixed Income",
      bestAccount: "IRA / 401k -- bond interest taxed as ordinary income annually.",
      rationale: "The most debated allocation in this environment. Intermediate Treasuries provide rate exposure.",
      instruments: [
        { name: "Long-Term Treasury Bond ETF", ticker: "TLT", type: "ETF" },
        { name: "Intermediate-Term Treasury Bond ETF", ticker: "IEF", type: "ETF" },
        { name: "EM Bonds Local Currency ETF", ticker: "EBND", type: "ETF" },
        { name: "Capital Group Core Plus Income ETF -- active...", ticker: "CGCP", type: "Active ETF" },
      ],
      caveat: "TLT is a thesis-dependent position. With CPI at 4.2% and the Fed on hold, long bonds carry.",
    },
    {
      id: "commodities", theme: "Commodities Basket", weight: "5%",
      signal: "green", conviction: "Medium", assetClass: "Commodities",
      bestAccount: "Taxable for PDBC, PDBA, EVMT -- no K-1, no administrative burden. IRA for DBC.",
      rationale: "Broad inflation hedge. Energy CPI at 23.5%, food price pressure building into Q4.",
      instruments: [
        { name: "Invesco Optimum Yield Diversified Commodity...", ticker: "PDBC", type: "ETF" },
        { name: "Invesco Agriculture Commodity Strategy -- food as...", ticker: "PDBA", type: "ETF" },
        { name: "Invesco EV Metals Commodity Strategy -- lithium,...", ticker: "EVMT", type: "ETF" },
        { name: "Invesco DB Commodity Index Tracking Fund -- broad...", ticker: "DBC", type: "ETF" },
      ],
      caveat: "Critical tax note: commodity ETFs holding futures directly generate K-1 forms in taxable.",
    },
    {
      id: "healthcare-broad", theme: "Healthcare", weight: "3-5% new position",
      signal: "green", conviction: "High", assetClass: "Equities",
      bestAccount: "Taxable -- qualified dividends at lower tax rate. Roth IRA for highest-growth.",
      rationale: "Healthcare demand is non-discretionary. People do not stop needing medication or insurance when inflation is.",
      instruments: [
        { name: "Health Care Select Sector SPDR -- broad exposure", ticker: "XLV", type: "ETF" },
        { name: "Vanguard Health Care ETF -- lower expense ratio", ticker: "VHT", type: "ETF" },
        { name: "Capital Group Health Care ETF -- active, tilts...", ticker: "CGHC", type: "Active ETF" },
        { name: "Eli Lilly -- GLP-1 tailwind, largely macro-independent", ticker: "LLY", type: "Stock" },
      ],
      caveat: "Avoid healthcare REITs (WELL, VTR) -- rate-sensitive like all REITs. Medical devices more.",
    },
  ],
  caution: [
    { id: "c0", theme: "S&P 500 Index Funds -- Know What You Own",
      reason: "Index funds are not bad -- they are the right answer most of the time.",
      instruments: [
        { name: "SPDR S&P 500 ETF", ticker: "SPY", type: "Caution" },
        { name: "Vanguard S&P 500 ETF", ticker: "VOO", type: "Caution" },
        { name: "iShares Core S&P 500 ETF", ticker: "IVV", type: "Caution" },
      ],
    },
    { id: "c05", theme: "American Balanced / 60/40 Funds and Fund-of-Funds",
      reason: "Two cautions. American Balanced (ABALX) is classic 60/40 in active clothing --.",
      instruments: [
        { name: "American Balanced Fund", ticker: "ABALX", type: "Caution" },
        { name: "Income Fund of America", ticker: "AMECX", type: "Caution" },
        { name: "Growth and Income Portfolio -- fund-of-funds,...", ticker: "GAIOX", type: "Caution" },
      ],
    },
    { id: "c06", theme: "Growth Fund of America",
      reason: "Large cap U.S. growth tilt at Shiller CAPE 39.9. High-quality management does.",
      instruments: [
        { name: "Growth Fund of America", ticker: "AGTHX", type: "Caution" },
        { name: "American Funds New Perspective", ticker: "ANWPX", type: "Caution" },
      ],
    },
    { id: "c1", theme: "Long-Duration Bonds (standalone)",
      reason: "TLT held outside the Warsh cut thesis carries pure duration risk.",
      instruments: [
        { name: "iShares 20+ Year Treasury Bond ETF", ticker: "TLT", type: "Caution" },
        { name: "Vanguard Long-Term Treasury ETF", ticker: "VGLT", type: "Caution" },
      ],
    },
    { id: "c2", theme: "Dollar Store / Lower-K Consumer",
      reason: "Dollar General and Dollar Tree look defensive but are not.",
      instruments: [
        { name: "Dollar General", ticker: "DG", type: "Caution" },
        { name: "Dollar Tree / Family Dollar", ticker: "DLTR", type: "Caution" },
        { name: "Darden Restaurants -- casual dining", ticker: "DRI", type: "Caution" },
      ],
    },
    { id: "c3", theme: "Consumer Discretionary Broad",
      reason: "Real wages negative, SNAP cuts October 1, savings at 2.6%.",
      instruments: [
        { name: "Consumer Discretionary Select Sector SPDR", ticker: "XLY", type: "Caution" },
        { name: "Vanguard Consumer Discretionary ETF", ticker: "VCR", type: "Caution" },
      ],
    },
    { id: "c4", theme: "ARK Innovation / High-Duration Growth",
      reason: "High-multiple growth stocks are vulnerable if the Fed holds or is forced to.",
      instruments: [
        { name: "ARK Innovation ETF", ticker: "ARKK", type: "Caution" },
        { name: "ARK Next Generation Internet ETF", ticker: "ARKW", type: "Caution" },
      ],
    },
    { id: "c5", theme: "REITs",
      reason: "Mortgage rates at 6.55%, FHA delinquency at 11.52%, foreclosure pipeline.",
      instruments: [
        { name: "Vanguard Real Estate ETF", ticker: "VNQ", type: "Caution" },
        { name: "Realty Income -- net lease REIT", ticker: "O", type: "Caution" },
        { name: "Welltower -- healthcare REIT", ticker: "WELL", type: "Caution" },
      ],
    },
  ],
  consider: [
    {
      id: "qual", theme: "Quality Factor Screen", ticker: "QUAL",
      signal: "yellow", conviction: "High", assetClass: "Equities",
      bestAccount: "Taxable -- low turnover means minimal annual tax drag. Long-term capital gains.",
      rationale: "The model has Large Cap Equal Weight at 2.5% but no quality filter.",
      instruments: [
        { name: "iShares MSCI USA Quality Factor ETF", ticker: "QUAL", type: "ETF" },
        { name: "Capital Group Conservative Equity ETF -- same team...", ticker: "CGCV", type: "Active ETF" },
      ],
      caveat: "Quality stocks still carry market risk. They outperform in relative terms but still fall in a.",
    },
    {
      id: "dividends", theme: "Dividend Income", ticker: "VIG, DVY",
      signal: "yellow", conviction: "Medium", assetClass: "Equities",
      bestAccount: "Taxable for qualified dividends (lower tax rate).",
      rationale: "Real wages are negative. Consumers need income from somewhere.",
      instruments: [
        { name: "Vanguard Dividend Appreciation ETF -- dividend...", ticker: "VIG", type: "ETF" },
        { name: "iShares Select Dividend ETF -- current yield focus", ticker: "DVY", type: "ETF" },
        { name: "Schwab U.S. Dividend Equity ETF", ticker: "SCHD", type: "ETF" },
        { name: "Capital Group Dividend Value ETF -- active, avoids...", ticker: "CGDV", type: "Active ETF" },
      ],
      caveat: "Dividend stocks are rate-sensitive. If rates rise further, high-yield dividend stocks face.",
    },
    {
      id: "staples", theme: "Consumer Staples", ticker: "VDC, XLP",
      signal: "yellow", conviction: "Medium", assetClass: "Equities",
      bestAccount: "Taxable -- low turnover, qualified dividends. Works in IRA too.",
      rationale: "This is not a lower-K play. It is an upper-K defensive play. Lower-K households are cutting spending.",
      instruments: [
        { name: "Vanguard Consumer Staples ETF", ticker: "VDC", type: "ETF" },
        { name: "Consumer Staples Select Sector SPDR", ticker: "XLP", type: "ETF" },
      ],
      caveat: "Staples are not immune to inflation -- input costs rise with energy and food prices. Actively.",
    },
    {
      id: "japan", theme: "Japan (Developed International Tilt)", ticker: "EWJ",
      signal: "yellow", conviction: "Medium", assetClass: "International Equities",
      bestAccount: "Taxable -- foreign tax credits on Japanese dividends are only usable in taxable.",
      rationale: "Within developed international exposure, Japan deserves a specific allocation. Weak yen makes Japanese.",
      instruments: [
        { name: "iShares MSCI Japan ETF", ticker: "EWJ", type: "ETF" },
        { name: "WisdomTree Japan Hedged Equity Fund -- currency hedged", ticker: "DXJ", type: "ETF" },
        { name: "Capital Group International Equity ETF -- active,...", ticker: "CGIE", type: "Active ETF" },
      ],
      caveat: "DXJ hedges out the yen, which is better if the dollar strengthens.",
    },
    {
      id: "stablecoin-infra", theme: "Stablecoin & Payment Infrastructure", ticker: "V, MA, COIN",
      signal: "green", conviction: "High", assetClass: "Equities",
      bestAccount: "Taxable -- long-term capital gains if held over a year. V and MA are.",
      rationale: "The petrodollar agreement expired June 2024 with no renewal. The dollar cannot maintain global dominance.",
      instruments: [
        { name: "Visa -- X Money runs on Visa Direct, Trusted Agent...", ticker: "V", type: "Stock" },
        { name: "Mastercard -- BVNK acquisition, Agent Pay, Recorded...", ticker: "MA", type: "Stock" },
        { name: "Coinbase -- JPM Coin launched on Base,...", ticker: "COIN", type: "Stock" },
      ],
      caveat: "Pure crypto plays (BTC, ETH) are volatile and speculative -- not infrastructure. Circle (USDC.",
    },
    {
      id: "ai-surveillance", theme: "AI & Surveillance Infrastructure", ticker: "PLTR, NVDA, MSI, AXON",
      signal: "red", conviction: "High", assetClass: "Equities",
      bestAccount: "Roth IRA for PLTR and NVDA if you believe in multi-year compounding. Taxable.",
      rationale: "This is not a recommendation to buy AI because it is exciting. These are specific companies building the.",
      instruments: [
        { name: "Palantir -- U.S. government surveillance...", ticker: "PLTR", type: "Stock" },
        { name: "Nvidia -- data center and government inference compute", ticker: "NVDA", type: "Stock" },
        { name: "Motorola Solutions -- video surveillance, command...", ticker: "MSI", type: "Stock" },
        { name: "Axon Enterprise -- body cameras, Fusus network...", ticker: "AXON", type: "Stock" },
        { name: "Constellation Energy -- nuclear power for AI data...", ticker: "CEG", type: "Stock" },
        { name: "Broadcom -- custom AI chips for hyperscalers, less...", ticker: "AVGO", type: "Stock" },
      ],
      caveat: "Palantir is the most direct play and the most ethically complex. Investing in Palantir is.",
    },
    {
      id: "cash", theme: "Cash Buffer", ticker: "SGOV, Money Market",
      signal: "green", conviction: "High", assetClass: "Cash",
      bestAccount: "Taxable -- state tax exemption on T-bill interest is only useful in taxable.",
      rationale: "The model carries 0.5% cash. In an environment where Stage 3 contagion arrives in Q4, having 5 to 10% in cash.",
      instruments: [
        { name: "iShares 0-3 Month Treasury Bond ETF", ticker: "SGOV", type: "ETF" },
        { name: "Fidelity Government Money Market Fund", ticker: "SPAXX", type: "Fund" },
        { name: "Vanguard Federal Money Market Fund", ticker: "VMFXX", type: "Fund" },
        { name: "X Money -- 6% APY, FDIC-insured via Cross River...", ticker: "X Money", type: "Platform" },
      ],
      caveat: "X Money platform risk: X controls your account through its terms of service. If your account.",
    },
  ],
};

export default monitorData;
